name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: npm ci
    - name: Lint code
      run: npm run lint
    - name: Run tests
      run: npm test
    - name: Build Playground
      run: npm run build-playground
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@3bdd7da
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web
